name = "ROSE"
uuid = "99d987ce-9a1e-4df8-bc0b-1ea019aa547b"
authors = ["Paul Tiede"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
