name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags: '*'
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.group == 'Downstream'}}
    strategy:
      fail-fast: false
      matrix:
        group:
          - Core 
          - ComradeAdaptMCMC
          - ComradeAHMC
          - ComradeDynesty
          - ComradeOptimization
          - ComradeNested
        version:
          - '1.9'
          - '1'
        os:
          - ubuntu-latest
        arch:
          - x64
        python-version:
          - '3.10'
        

    steps:
      - name: Install Libs
        run: |
          sudo apt-get update
          sudo apt-get install libhdf5-dev
          sudo apt-get install --reinstall libxcb-xinerama0
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.arch }}

      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@v1      
      - uses: actions/cache@v3
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-

      - uses: julia-actions/julia-runtest@v1
        env:
          GROUP: ${{ matrix.group }}
      - uses: julia-actions/julia-processcoverage@v1
        with:
          directories: src,lib/ComradeOptimization/src,lib/ComradeAHMC/src,lib/ComradeDynesty/src,lib/ComradeNested/src,lib/ComradeAdaptMCMC/src
      - uses: codecov/codecov-action@v3
        with:
          file: lcov.info
